theme: jekyll-theme-minimal
logo: https://mrpaulandrew.github.io/ADF.procfwk/thumbnail.png
title: ADF.procfwk
description: A metadata driven processing framework for Azure Data Factory (ADF) achieved by coupling ADF with an Azure SQLDB and Azure Functions.<br/><br/><a href="/ADF.procfwk/index"> - Overview</a><br/><a href="/ADF.procfwk/contents"> - Contents</a>
baseurl: /ADF.procfwk