theme: jekyll-theme-minimal
logo: https://mrpaulandrew.github.io/ADF.procfwk/thumbnail.png
title: ADF.procfwk
description: <hr/>A metadata driven processing framework for Azure Data Factory (ADF) achieved by coupling ADF with an Azure SQLDB and Azure Functions.<hr/><ul><li><a href="https://mrpaulandrew.github.io/ADF.procfwk/">Overview</a></li><li><a href="https://mrpaulandrew.github.io/ADF.procfwk/contents">Contents</a></li></ul><hr/>